# Generated by Django 5.2.6 on 2025-09-06 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transacao',
            name='pago',
        ),
        migrations.AddField(
            model_name='transacao',
            name='data_pagamento',
            field=models.DateField(blank=True, null=True, verbose_name='Data do Pagamento'),
        ),
    ]
