# Generated by Django 5.2.6 on 2025-09-07 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contabancaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='conta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.contabancaria', verbose_name='Conta'),
        ),
    ]
