# Generated by Django 5.2.6 on 2025-09-07 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_transacao_conta'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartaoCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Cartão')),
                ('limite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dia_fechamento', models.PositiveIntegerField(verbose_name='Dia do Fechamento da Fatura')),
                ('dia_vencimento', models.PositiveIntegerField(verbose_name='Dia do Vencimento da Fatura')),
            ],
            options={
                'verbose_name_plural': 'Cartões de Crédito',
            },
        ),
        migrations.CreateModel(
            name='Fatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_referencia', models.DateField(verbose_name='Mês de Referência')),
                ('data_fechamento', models.DateField()),
                ('data_vencimento', models.DateField()),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('paga', models.BooleanField(default=False)),
                ('cartao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faturas', to='core.cartaocredito')),
                ('transacao_pagamento', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.transacao')),
            ],
            options={
                'unique_together': {('cartao', 'mes_referencia')},
            },
        ),
        migrations.CreateModel(
            name='DespesaCartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('valor', models.DecimalField(decimal_places=2, help_text='Use um valor negativo para estornos', max_digits=10)),
                ('data', models.DateField(verbose_name='Data da Compra')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.categoria')),
                ('fatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despesas', to='core.fatura')),
            ],
        ),
    ]
