# Generated by Django 5.2.6 on 2025-09-09 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_cartaocredito_fatura_despesacartao'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompraParcelada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('numero_parcelas', models.PositiveIntegerField()),
                ('data_compra', models.DateField()),
                ('cartao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cartaocredito')),
            ],
        ),
        migrations.CreateModel(
            name='TransacaoCartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('valor', models.DecimalField(decimal_places=2, help_text='Use um valor negativo para estornos', max_digits=10)),
                ('data', models.DateField(verbose_name='Data da Compra')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.categoria')),
                ('compra_parcelada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='core.compraparcelada')),
                ('fatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacoes', to='core.fatura')),
            ],
            options={
                'verbose_name': 'Transação de Cartão',
                'verbose_name_plural': 'Transações de Cartão',
            },
        ),
        migrations.DeleteModel(
            name='DespesaCartao',
        ),
    ]
