# Generated by Django 5.2.6 on 2025-09-10 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_compraparcelada_transacaocartao_delete_despesacartao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='conta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.contabancaria', verbose_name='Conta'),
        ),
    ]
