# Generated by Django 5.2.6 on 2025-09-10 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_transacao_conta'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='icone',
            field=models.CharField(blank=True, help_text='Classe CSS do ícone (ex: bi bi-house, bi bi-car). Consulte Bootstrap Icons.', max_length=50, null=True),
        ),
    ]
